# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FlowPlotter
                                 A QGIS plugin
 Draw a plot for feature selected.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-11-07
        copyright            : (C) 2024 by xiaotianxt
        email                : tianyp@pku.edu.cn
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load FlowPlotter class from file FlowPlotter.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .flow_plotter import FlowPlotter
    return FlowPlotter(iface)
