# -*- coding: utf-8 -*-
"""
/***************************************************************************
 FlowPlotterDockWidget
                                 A QGIS plugin
 Draw a plot for feature selected.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-11-07
        git sha              : $Format:%H$
        copyright            : (C) 2024 by xiaotianxt
        email                : tianyp@pku.edu.cn
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
import numpy as np
import matplotlib
from typing import List

matplotlib.use("Agg")
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.backends.backend_qt5agg import NavigationToolbar2QT as NavigationToolbar
from matplotlib.figure import Figure
from qgis.PyQt import QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal
from qgis.core import QgsMapLayerProxyModel, QgsVectorLayer, QgsProject, QgsMapLayer
from qgis.gui import QgsMapLayerComboBox
from qgis.utils import iface

FORM_CLASS, _ = uic.loadUiType(os.path.join(os.path.dirname(__file__), "flow_plotter_dockwidget_base.ui"))


class FlowPlotterDockWidget(QtWidgets.QDockWidget, FORM_CLASS):
    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        super(FlowPlotterDockWidget, self).__init__(parent)
        # Set up the user interface from Designer.
        # After setupUI you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://doc.qt.io/qt-5/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.init_plot()
        iface.currentLayerChanged.connect(self.on_active_layer_changed)
        self.layer = iface.layerTreeView().selectedLayers()[0] if iface.layerTreeView().selectedLayers() else None
        self.on_active_layer_changed(self.layer)
        print(self.layer)

    def init_plot(self):
        layout = self.verticalLayout  # Use the layout defined in the .ui file

        static_canvas = FigureCanvas(Figure(figsize=(5, 3)))
        self.static_canvas = static_canvas
        static_canvas.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        static_canvas.updateGeometry()

        layout.addWidget(NavigationToolbar(static_canvas, self))
        layout.addWidget(static_canvas)

    def on_active_layer_changed(self, layer: QgsMapLayer):
        # Only disconnect if we're connected
        if isinstance(self.layer, QgsVectorLayer):
            try:
                while True:
                    self.layer.disconnect(self.on_selection_changed)
            except TypeError:
                pass  # Ignore if not connected

        if isinstance(layer, QgsVectorLayer):
            print("[Layer]", layer.name())
            self.layer = layer
            self.layer.selectionChanged.connect(self.on_selection_changed)

    def on_selection_changed(self, selections: List[int]):
        if not len(selections):
            return

        print("[Feature]", selections[0])
        feature = self.layer.getFeature(selections[0])

        # 清除旧图
        self.static_canvas.figure.clear()

        # 创建新的子图
        self._static_ax = self.static_canvas.figure.add_subplot(111)

        # 绘制新图
        import random

        t = np.linspace(0, 10, random.randint(100, 200))
        self._static_ax.plot(t, np.tan(t), ".")
        self._static_ax.set_title("Tan plot")

        # 刷新画布
        self.static_canvas.draw()

    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()
